### ISSUE TITLE
Could not launch app in GitHub 

### ISSUE THREAD

**Issue by JaredBears** [appdev-projects/industrial-auth-1#1]
When launching the app I received the following error:

```
Blocked host: ~.app.github.dev
To allow requests ~.app.github.dev make sure it is a valid hostname (containing only numbers, letters, dashes and dots), then add the following to your environment configuration:

config.hosts << "~.app.github.dev"
For more details view: the Host Authorization guid
```

I fixed it by adding the line `config.hosts << /.*\.app\.github\.dev/` to the development environment file.  It looks like previous projects have fixed it by using the line `config.hosts.clear`

**Comment by bpurinton** [comment]
Nice catch, not sure why that wasn't in there to begin with: https://github.com/appdev-projects/industrial-auth-1/commit/0ea8ec2a1969a9b9baf6d8ad9c96d7c10b87e40b
