### ISSUE TITLE
Sample data task refinement

### ISSUE THREAD

**Issue by armstrca** [appdev-projects/industrial-auth-1#38]
For ease of grading, it might be useful to have a more testing-minded sample_data task with hard-coded user scenarios. 
For example, making sure that 'Bob' has a private profile, doesn't follow `current_user` and is not followed by `current_user` would be useful to a TA because we could always add `/bob` to the url to check that a trainee's policy is properly handling that scenario. 

As it currently stands, there's no way to tell which users generated by `rake sample_data` fit this or other scenarios without semi-randomly clicking around the site, and technically there's no guarantee that each relevant scenario would be generated in a given run of `rake sample_data`.

**Comment by bpurinton** [comment]
Point well taken! I wasn't aware you all were grading students in this manual manner. (I.e. our later projects don't have detailed `rake grade` specs, which are more beginner-minded.)

I should have some time later today to submit a fix. I think just using a "seed" on Faker might work.. I'll look into it.

**Comment by bpurinton** [comment]
@armstrca, I added you as a collaborator on this repo and opened this PR for you to review: https://github.com/appdev-projects/industrial-auth-1/pull/39

I'm not exactly sure on the requirements for grading / what would be most helpful for the TAs, so we can edit the task further depending on needs.
